Repository sinfo/cannon-api, pull requests merged in 2023-02, with the labels that each got.

#183 Tickets multiple fixes
  package.json
  server/helpers/google.js
  server/resources/email.js
  server/resources/happy-hour.js
  server/resources/session.js
  server/resources/ticket.js
  server/resources/user.js
  server/routes/achievement/handlers.js
  server/routes/auth/handlers.js
  server/routes/company-endpoint/handlers.js
  server/routes/file/handlers.js
  server/routes/link/handlers.js
  server/routes/promo-code/handlers.js
  server/routes/redeem/handlers.js
  server/routes/sign/handlers.js
  server/routes/ticket/handlers.js
  server/routes/user/handlers.js
Labels: bug

#189 Feature: Fetch everything from deck
  config.js
  package.json
  server/plugins/aws.js
  server/plugins/index.js
  server/resources/achievement.js
  server/resources/deck.js
  server/resources/index.js
  server/resources/user.js
  server/routes/achievement/handlers.js
  server/routes/company-endpoint/handlers.js
  server/routes/deck/handlers.js
  server/routes/deck/index.js
  server/routes/file/handlers.js
  server/routes/index.js
  server/routes/link/handlers.js
  server/routes/sign/handlers.js
  server/routes/user/handlers.js
  server/test/achievement.js
  server/test/user.js
  server/views/company.js
  server/views/event.js
  server/views/member.js
  server/views/session.js
  server/views/speaker.js
Labels: feature

#195 Update 2.1.0
  config.js
  package.json
  server/plugins/aws.js
  server/plugins/index.js
  server/resources/achievement.js
  server/resources/deck.js
  server/resources/index.js
  server/resources/user.js
  server/routes/achievement/handlers.js
  server/routes/company-endpoint/handlers.js
  server/routes/deck/handlers.js
  server/routes/deck/index.js
  server/routes/file/handlers.js
  server/routes/index.js
  server/routes/link/handlers.js
  server/routes/sign/handlers.js
  server/routes/user/handlers.js
  server/test/achievement.js
  server/test/user.js
  server/views/company.js
  server/views/event.js
  server/views/member.js
  server/views/session.js
  server/views/speaker.js
Labels: update

#191 Feature: Reverse Links
  server/db/link.js
  server/resources/link.js
  server/resources/user.js
  server/routes/link/handlers.js
  server/routes/link/index.js
  server/routes/user/handlers.js
  server/views/link.js
  server/views/user.js
Labels: feature

#196 Fix: Fix related to links
  server/resources/link.js
  server/routes/link/handlers.js
Labels: fix

#197 Update 2.1.1
  server/db/achievement.js
  server/db/link.js
  server/resources/achievement.js
  server/resources/link.js
  server/resources/user.js
  server/routes/achievement/handlers.js
  server/routes/link/handlers.js
  server/routes/link/index.js
  server/routes/user/handlers.js
  server/views/link.js
  server/views/user.js
Labels: update

#198 Feature: Getting sessions without achievements
  server/resources/deck.js
  server/routes/deck/handlers.js
Labels: feature

#202 Feature: Share links with other users
  server/db/user.js
  server/resources/link.js
  server/resources/user.js
  server/routes/link/handlers.js
  server/routes/link/index.js
  server/routes/sign/handlers.js
  server/views/user.js
Labels: feature

#203 Update 2.1.3
  server/db/user.js
  server/resources/achievement.js
  server/resources/link.js
  server/resources/ticket.js
  server/resources/user.js
  server/routes/link/handlers.js
  server/routes/link/index.js
  server/routes/sign/handlers.js
  server/routes/ticket/handlers.js
  server/views/user.js
Labels: update

#206 Fix: Validate sharing permission activation
  server/resources/user.js
  server/routes/link/handlers.js
Labels: fix

#207 Update 2.1.6
  server/resources/user.js
  server/routes/link/handlers.js
Labels: update

#208 pick winner fix
  server/routes/deck/index.js
Labels: fix

#210 Fix: Fix CVs
  server/resources/link.js
Labels: fix
